type User {
  id: Int!
  username: String!
  email: String!
  teams: [Team!]!
}

type Query {
  getUser(id: Int!): User!
  Users: [User!]
}

type Mutation {
  register(username: String!, email: String!, password: String!): Boolean!
}
